const foodItems = [
  {
    name: "Milk",
    calories: 65,
    protein: 3.5,
    fat: 4,
    carbs: 5,
    itemWeight: 100,
    accessible: "ml",
  },
  {
    name: "Butter",
    calories: 740,
    fat: 82,
    itemWeight: 100,
    accessible: "g",
  },
  {
    name: "Cream",
    calories: 210,
    protein: 2,
    fat: 21,
    carbs: 3,
    itemWeight: 100,
    accessible: "ml",
  },
  {
    name: "Cheese",
    calories: 310,
    protein: 22,
    fat: 25,
    itemWeight: 100,
    accessible: "g",
  },
  {
    name: "Ice Cream",
    calories: 170,
    protein: 4,
    fat: 7,
    carbs: 25,
    itemWeight: 100,
    accessible: "ml",
  },
  {
    name: "Margarine",
    calories: 740,
    fat: 81,
    itemWeight: 100,
    accessible: "g",
  },
  {
    name: "Eggs",
    calories: 150,
    protein: 12,
    fat: 11,
    itemWeight: 100,
    accessible: "g",
  },
  {
    name: "Pork",
    calories: 340,
    protein: 29,
    fat: 24,
    itemWeight: 100,
    accessible: "g",
  },
  {
    name: "Chicken",
    calories: 150,
    protein: 125,
    fat: 5,
    itemWeight: 100,
    accessible: "kg",
  },
  {
    name: "Fish",
    calories: 220,
    protein: 20,
    fat: 10,
    carbs: 8,
    itemWeight: 100,
    accessible: "kg",
  },
  {
    name: "Beans",
    calories: 20,
    protein: 2,
    carbs: 3,
    itemWeight: 100,
    accessible: "g",
  },
  {
    name: "Cabbage",
    calories: 10,
    protein: 1,
    carbs: 1,
    itemWeight: 100,
    accessible: "g",
  },
  {
    name: "Carrot",
    calories: 20,
    protein: 0.6,
    carbs: 4,
    itemWeight: 100,
    accessible: "g",
  },
  {
    name: "Cauliflower",
    calories: 10,
    protein: 1.5,
    carbs: 1,
    itemWeight: 93,
    accessible: "g",
  },
  {
    name: "Cucumber",
    calories: 10,
    protein: 0.6,
    carbs: 0.2,
    itemWeight: 100,
    accessible: "g",
  },
  {
    name: "Apples",
    calories: 45,
    protein: 0.3,
    carbs: 12,
    itemWeight: 100,
    accessible: "g",
  },
  {
    name: "Bananas",
    calories: 80,
    protein: 1,
    carbs: 20,
    itemWeight: 100,
    accessible: "g",
  },
  {
    name: "Cherries",
    calories: 50,
    protein: 0.6,
    carbs: 12,
    itemWeight: 100,
    accessible: "g",
  },
  {
    name: "Pea Nuts",
    calories: 570,
    protein: 24,
    fat: 49,
    carbs: 9,
    itemWeight: 100,
    accessible: "g",
  },
  {
    name: "Bread",
    calories: 230,
    protein: 8,
    fat: 2,
    carbs: 50,
    itemWeight: 100,
    accessible: "g",
  },
]
